CREATE TABLE TIPO_DOCUMENTO (
   NR INT PRIMARY KEY,
   NOME VARCHAR(40)
  
);

CREATE TABLE DOCUMENTO (
    NUMERO INT PRIMARY KEY,
    NOME VARCHAR(100),
    TIPO INT
);
 
ALTER TABLE DOCUMENTO ADD CONSTRAINT FK_DOCUMENTO_2
    FOREIGN KEY (TIPO)
    REFERENCES TIPO_DOCUMENTO (NR)
    ON DELETE CASCADE;