
INSERT INTO TIPO_DOCUMENTO VALUES ( 1, 'OFICIO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 2, 'PARTE');
INSERT INTO TIPO_DOCUMENTO VALUES ( 3, 'MEMORANDO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 4, 'RELATORIO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 5, 'REQUERIMENTO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 6, 'MEMORIA');
INSERT INTO TIPO_DOCUMENTO VALUES ( 7, 'PROJETO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 8, 'ORÇAMENTO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 9, 'PEDIDO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 10, 'REQUISITOS');
INSERT INTO TIPO_DOCUMENTO VALUES ( 11, 'ORDEM DE COMPRA');
INSERT INTO TIPO_DOCUMENTO VALUES ( 12, 'ORDEM DE VENDA');
INSERT INTO TIPO_DOCUMENTO VALUES ( 13, 'CONTRATO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 14, 'LAUDO');
INSERT INTO TIPO_DOCUMENTO VALUES ( 15, 'TERMO DE RESPONSABILIDADE');



DO $$
DECLARE
    i INTEGER := 1;
BEGIN
    WHILE i <= 50000 LOOP
        INSERT INTO DOCUMENTO(numero, nome, tipo)
        VALUES (i, 'documento' || i::TEXT, (random() * 14)::INTEGER + 1);
        i := i + 1;
    END LOOP;
END $$;
 
 